# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b40d1f31cdc91e4413c5ba72ce65dae41eec67a3edc18a82e24d2d5b8ddf12afeef6be0aafad8a835bfb65ec3567b57654897fa0a5cbe21cd5c70e00262302d

test:
  secret_key_base: 769a203c90f236826e7ad6ae7fb20710e8b19f4da4d177af9b0f4b56a334a320ddb71a81e7e463b9608003016dbdcd64233de0b5b023acbcb91b1ce87d533569

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
